import { Platform, StyleSheet } from 'react-native';
import { Colors, Radius, Shadows, Spacing, Typography } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    zIndex: 50,
    elevation: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  greeting: { fontSize: Typography.sm, color: Colors.gray400 },
  userName: { fontSize: Typography.xl, fontWeight: Typography.bold },
  dateLabel: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  headerActions: { position: 'relative', flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  helpButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: Colors.gray50,
    borderWidth: 1,
    borderColor: Colors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationDot: {
    position: 'absolute',
    top: 7,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.danger,
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: Colors.green50,
    borderWidth: 1,
    borderColor: Colors.green100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerMenu: {
    position: 'absolute',
    top: 50,
    right: 0,
    width: 190,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.white,
    paddingVertical: 6,
    zIndex: 100,
    ...Shadows.md,
  },
  headerMenuItem: {
    minHeight: 42,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  headerMenuText: {
    flex: 1,
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.semibold,
  },
  headerMenuTextDanger: { color: Colors.danger },
  headerMenuBadge: {
    minWidth: 22,
    overflow: 'hidden',
    borderRadius: Radius.full,
    backgroundColor: Colors.danger,
    paddingHorizontal: 6,
    paddingVertical: 2,
    color: Colors.white,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    textAlign: 'center',
  },
  settingsButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: Colors.green50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImage: { width: 48, height: 48, borderRadius: 24 },
  avatarText: { fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.green600 },
  gearBadge: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.green600,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: Colors.white,
  },

  scroll: { padding: Platform.OS === 'web' ? Spacing.xl : 0, paddingBottom: 100 },
  desktopTopGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  desktopSummaryColumn: {
    flex: 0.9,
    minWidth: 360,
  },
  desktopPlanColumn: {
    flex: 1.35,
    minWidth: 460,
  },
  ringSection: { backgroundColor: Colors.white, padding: Spacing.base, marginBottom: Spacing.sm },
  ringWrap: { alignItems: 'center', marginBottom: Spacing.md, position: 'relative' },
  ringCenter: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, alignItems: 'center', justifyContent: 'center' },
  ringKcal: { fontSize: Typography.xxl, fontWeight: Typography.bold },
  ringKcalSub: { fontSize: Typography.xs, color: Colors.gray400 },
  ringGoal: { fontSize: Typography.sm, color: Colors.gray400 },
  remainRow: { flexDirection: 'row', justifyContent: 'space-around' },
  remainItem: { alignItems: 'center', flex: 1 },
  remainCenter: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: Colors.border, paddingHorizontal: Spacing.sm },
  remainVal: { fontSize: Typography.lg, fontWeight: Typography.bold },
  remainLabel: { fontSize: Typography.xs, color: Colors.gray400 },

  foodPlanPanel: {
    marginHorizontal: Platform.OS === 'web' ? 0 : Spacing.base,
    marginBottom: Spacing.sm,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  foodPlanHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: Spacing.sm, marginBottom: Spacing.sm },
  foodPlanEyebrow: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold, textTransform: 'uppercase', letterSpacing: 0.4 },
  foodPlanTitle: { marginTop: 2, fontSize: Typography.lg, color: Colors.gray800, fontWeight: Typography.bold },
  foodPlanAuthor: { fontSize: Typography.xs, color: Colors.gray400, fontWeight: Typography.bold },
  foodPlanNotes: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 19, marginBottom: Spacing.sm },
  foodPlanCompleteBox: { minHeight: 58, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.green100, backgroundColor: Colors.green50, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, padding: Spacing.sm },
  foodPlanCompleteText: { flex: 1, fontSize: Typography.sm, color: Colors.green600, fontWeight: Typography.bold, lineHeight: 18 },
  foodPlanMeal: { backgroundColor: Colors.gray50, borderRadius: Radius.md, padding: Spacing.sm, marginBottom: Spacing.xs },
  foodPlanMealSkipped: { opacity: 0.72 },
  foodPlanMealHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: Spacing.sm },
  foodPlanMealHeaderText: { flex: 1 },
  foodPlanMealTitle: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  foodPlanOptionLabel: { marginTop: 2, fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold },
  foodPlanMealHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  foodPlanShoppingIconBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  foodPlanDropdownBtn: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  foodPlanDropdown: { marginTop: Spacing.xs, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.sm, overflow: 'hidden', backgroundColor: Colors.white },
  foodPlanDropdownItem: { minHeight: 38, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, paddingHorizontal: Spacing.sm, borderTopWidth: 1, borderTopColor: Colors.border },
  foodPlanDropdownItemActive: { backgroundColor: Colors.green50 },
  foodPlanDropdownText: { flex: 1, fontSize: Typography.sm, color: Colors.gray600, fontWeight: Typography.semibold },
  foodPlanDropdownTextActive: { color: Colors.green600 },
  foodPlanMealItems: { marginTop: 3, fontSize: Typography.xs, color: Colors.gray600, lineHeight: 17 },
  foodPlanMealNutrition: { marginTop: 4, fontSize: Typography.xs, color: Colors.gray400, lineHeight: 17 },
  foodPlanMealActions: { marginTop: Spacing.sm, flexDirection: 'row', gap: Spacing.xs },
  foodPlanSkipBtn: { minHeight: 38, paddingHorizontal: Spacing.sm, borderRadius: Radius.md, backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.border, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  foodPlanSkipBtnActive: { backgroundColor: Colors.gray600, borderColor: Colors.gray600 },
  foodPlanSkipText: { color: Colors.gray600, fontSize: Typography.sm, fontWeight: Typography.bold },
  foodPlanSkipTextActive: { color: Colors.white },
  foodPlanDoneBtn: { flex: 1, minHeight: 38, borderRadius: Radius.md, backgroundColor: Colors.green400, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
  foodPlanDoneBtnCompleted: { backgroundColor: Colors.green600 },
  foodPlanDoneBtnDisabled: { opacity: 0.65 },
  foodPlanDoneText: { color: Colors.white, fontSize: Typography.sm, fontWeight: Typography.bold },
  shoppingTitle: { marginTop: Spacing.sm, marginBottom: Spacing.xs, fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  shoppingItem: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, paddingVertical: 5 },
  shoppingText: { flex: 1, fontSize: Typography.sm, color: Colors.gray600 },
  nutritionPanel: {
    marginHorizontal: Platform.OS === 'web' ? 0 : Spacing.base,
    marginBottom: Spacing.sm,
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
    ...Shadows.sm,
  },
  nutritionHeader: { padding: Spacing.md, borderBottomWidth: 1, borderBottomColor: Colors.border },
  nutritionTitle: { fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.gray800 },
  nutritionSubtitle: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  nutritionSection: { borderBottomWidth: 1, borderBottomColor: Colors.border },
  nutritionSectionTitle: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: 6,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.green600,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    backgroundColor: Colors.green50,
  },
  nutritionRow: { paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderTopWidth: 1, borderTopColor: Colors.border },
  nutritionRowTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  nutritionName: { flex: 1, fontSize: Typography.sm, fontWeight: Typography.semibold, color: Colors.gray800 },
  nutritionValues: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray800 },
  nutritionGoalText: { fontSize: Typography.xs, fontWeight: Typography.regular, color: Colors.gray400 },
  nutritionMetaRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: 6 },
  nutritionBarBg: { flex: 1, height: 6, backgroundColor: Colors.gray50, borderRadius: Radius.full, overflow: 'hidden' },
  nutritionBarFill: { height: 6, borderRadius: Radius.full },
  nutritionStatus: {
    minWidth: 78,
    overflow: 'hidden',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    textAlign: 'center',
  },
});

export const modalStyles = StyleSheet.create({
  scroll: { paddingBottom: Spacing.base },
  photoRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.lg },
  photoButton: { width: 72, height: 72, borderRadius: 36, backgroundColor: Colors.green50, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: Colors.green100 },
  photo: { width: 72, height: 72, borderRadius: 36 },
  photoInitials: { fontSize: Typography.xl, fontWeight: Typography.bold, color: Colors.green600 },
  profileInfo: { flex: 1, minWidth: 0, gap: 0, justifyContent: 'center' },
  profileNameInput: { minHeight: 23, padding: 0, fontSize: Typography.lg, fontWeight: Typography.bold, color: Colors.gray800 },
  nicknameRow: { flexDirection: 'row', alignItems: 'center' },
  nicknamePrefix: { fontSize: Typography.sm, color: Colors.green600, fontWeight: Typography.bold, marginRight: 1 },
  nicknameInput: { flex: 1, minHeight: 19, padding: 0, fontSize: Typography.sm, color: Colors.green600, fontWeight: Typography.semibold },
  birthDateDisplay: { minHeight: 23, alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 4 },
  birthDateText: { fontSize: Typography.sm, color: Colors.gray600, fontWeight: Typography.semibold },
  birthDateRow: { minHeight: 32, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs },
  birthDateInput: { flex: 1, minHeight: 32, borderRadius: Radius.sm, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white, paddingHorizontal: Spacing.sm, fontSize: Typography.sm, color: Colors.gray800 },
  datePickerBtn: { width: 36, height: 36, borderRadius: Radius.sm, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  ageCard: { width: 62, minHeight: 62, borderRadius: Radius.md, backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100, alignItems: 'center', justifyContent: 'center' },
  ageValue: { fontSize: Typography.xl, color: Colors.green600, fontWeight: Typography.bold },
  ageLabel: { fontSize: Typography.xs, color: Colors.gray600, fontWeight: Typography.semibold },
  sectionTitle: { fontSize: Typography.base, fontWeight: Typography.bold, marginBottom: 3 },
  sectionHint: { fontSize: Typography.xs, color: Colors.gray400, lineHeight: 16 },
  fieldGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.lg },
  fieldWrap: { width: '48%' },
  label: { fontSize: Typography.xs, fontWeight: Typography.semibold, color: Colors.gray600, marginBottom: 6, textTransform: 'uppercase', letterSpacing: 0.4 },
  inputRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.sm, paddingHorizontal: Spacing.sm, backgroundColor: Colors.white },
  input: { flex: 1, paddingVertical: Spacing.sm, fontSize: Typography.base, color: Colors.gray800 },
  suffix: { fontSize: Typography.xs, color: Colors.gray400, marginLeft: 4 },
  segmentRow: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.lg },
  segment: { flex: 1, paddingVertical: Spacing.sm, alignItems: 'center', borderRadius: Radius.md, backgroundColor: Colors.gray50, borderWidth: 1, borderColor: Colors.border },
  segmentActive: { backgroundColor: Colors.green50, borderColor: Colors.green400 },
  segmentText: { color: Colors.gray600, fontWeight: Typography.semibold },
  segmentTextActive: { color: Colors.green600 },
  segmentWrap: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.lg },
  pill: { paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderRadius: Radius.full, backgroundColor: Colors.gray50, borderWidth: 1, borderColor: Colors.border },
  pillActive: { backgroundColor: Colors.green50, borderColor: Colors.green400 },
  pillText: { color: Colors.gray600, fontWeight: Typography.semibold, fontSize: Typography.sm },
  pillTextActive: { color: Colors.green600 },
  sectionHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.sm },
  goalActionRow: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'flex-end', gap: Spacing.xs, flex: 1 },
  recalcBtn: { width: 40, height: 40, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green400 },
  helpCard: {
    maxHeight: '82%',
    maxWidth: Platform.OS === 'web' ? 620 : undefined,
    marginHorizontal: Spacing.base,
    backgroundColor: Colors.white,
    borderRadius: Radius.xl,
    padding: Spacing.base,
    alignSelf: 'stretch',
  },
  helpScroll: { paddingBottom: Spacing.sm },
  helpIntro: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 20, marginBottom: Spacing.md },
  helpBlock: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: Spacing.md,
    marginBottom: Spacing.md,
  },
  helpBlockTitle: { fontSize: Typography.base, fontWeight: Typography.bold, marginBottom: 6 },
  helpText: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 20 },
  sourceLink: {
    fontSize: Typography.sm,
    color: Colors.green600,
    fontWeight: Typography.semibold,
    lineHeight: 22,
    marginBottom: 8,
  },
  helpFootnote: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    lineHeight: 18,
    backgroundColor: Colors.gray50,
    borderRadius: Radius.md,
    padding: Spacing.md,
  },
  emptyNotice: { alignItems: 'center', justifyContent: 'center', padding: Spacing.xl },
  emptyNoticeText: { marginTop: Spacing.sm, fontSize: Typography.sm, color: Colors.gray400, textAlign: 'center' },
  noticeCard: { backgroundColor: Colors.gray50, borderRadius: Radius.md, padding: Spacing.md, marginBottom: Spacing.sm },
  noticeCardRead: { opacity: 0.68 },
  noticeTitle: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray800, marginBottom: 4 },
  noticeText: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 19 },
  noticeMeta: { marginTop: 4, fontSize: Typography.xs, color: Colors.gray400 },
  noticeActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: Spacing.sm, marginTop: Spacing.md },
  noticeRejectBtn: { borderWidth: 1, borderColor: Colors.borderMd, borderRadius: Radius.full, paddingHorizontal: Spacing.md, paddingVertical: 8 },
  noticeRejectText: { fontSize: Typography.sm, color: Colors.gray600, fontWeight: Typography.bold },
  noticeAcceptBtn: { backgroundColor: Colors.green400, borderRadius: Radius.full, paddingHorizontal: Spacing.md, paddingVertical: 8 },
  noticeAcceptText: { fontSize: Typography.sm, color: Colors.white, fontWeight: Typography.bold },
});

export const waterStyles = StyleSheet.create({
  bg: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: Spacing.base },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: 'rgba(0,0,0,0.35)' },
  card: { width: '100%', maxWidth: 380, backgroundColor: Colors.white, borderRadius: Radius.xl, padding: Spacing.base, ...Shadows.lg },
  title: { fontSize: Typography.lg, fontWeight: Typography.bold, color: Colors.gray800, marginBottom: Spacing.md, textAlign: 'center' },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  option: { width: '48%', backgroundColor: Colors.carbsL, borderWidth: 1, borderColor: '#B9D8F4', borderRadius: Radius.md, padding: Spacing.md, alignItems: 'center' },
  optionTitle: { fontSize: Typography.lg, fontWeight: Typography.bold, color: Colors.info },
  optionSub: { marginTop: 3, fontSize: Typography.xs, color: Colors.gray600 },
});
