import { Platform, StyleSheet } from "react-native";
import {
  Colors,
  Radius,
  Shadows,
  Spacing,
  Typography,
} from "../../constants/theme";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    width: "100%",
    maxWidth: Platform.OS === "web" ? 900 : undefined,
    alignSelf: "center",
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    zIndex: 100,
  },
  headerIdentity: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  headerAvatar: {
    width: 40,
    height: 40,
    borderRadius: Radius.full,
    backgroundColor: Colors.green50,
    alignItems: "center",
    justifyContent: "center",
  },
  headerText: { flex: 1, minWidth: 0 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6, position: "relative", zIndex: 200 },
  headerNotifyBtn: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green50,
    borderWidth: 1,
    borderColor: Colors.green100,
    borderRadius: Radius.full,
  },
  headerNotificationDot: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colors.danger,
  },
  headerMenu: {
    position: "absolute",
    top: 48,
    right: 0,
    width: 218,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.white,
    paddingVertical: 6,
    zIndex: 300,
    ...Shadows.md,
  },
  headerMenuItem: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  headerMenuText: {
    flex: 1,
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.semibold,
  },
  headerMenuTextDanger: { color: Colors.danger },
  eyebrow: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.bold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  title: {
    fontSize: Typography.xl,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  subtitle: {
    marginTop: 2,
    fontSize: Typography.sm,
    color: Colors.gray400,
    lineHeight: 18,
  },
  scroll: {
    width: "100%",
    maxWidth: Platform.OS === "web" ? 900 : undefined,
    alignSelf: "center",
    padding: Spacing.base,
    paddingBottom: Spacing.xxl,
  },
  panel: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    padding: Spacing.base,
    marginBottom: Spacing.sm,
    ...Shadows.sm,
  },
  sectionTitle: {
    fontSize: Typography.base,
    fontWeight: Typography.bold,
    color: Colors.gray800,
    marginBottom: Spacing.sm,
  },
  sectionTitleNoMargin: {
    fontSize: Typography.base,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  sectionSubtitle: {
    marginTop: 3,
    fontSize: Typography.xs,
    color: Colors.gray400,
  },
  sectionHeaderRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  patientActionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    gap: Spacing.xs,
    flex: 1,
  },
  chatBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.green50,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
  },
  chatBtnText: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  inviteRow: { flexDirection: "row", gap: Spacing.sm, marginTop: Spacing.sm },
  inviteInput: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    minHeight: 44,
    fontSize: Typography.sm,
    color: Colors.gray800,
  },
  inviteBtn: {
    minWidth: 92,
    minHeight: 44,
    borderRadius: Radius.md,
    backgroundColor: Colors.green400,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: Spacing.md,
  },
  inviteBtnText: {
    color: Colors.white,
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
  },
  patientRow: { gap: Spacing.sm },
  patientCard: {
    width: 180,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: Colors.gray50,
  },
  patientCardActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  patientNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
  },
  patientName: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  patientNameActive: { color: Colors.green600 },
  patientUnreadBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: Colors.green400,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 6,
  },
  patientUnreadText: {
    fontSize: Typography.xs,
    color: Colors.white,
    fontWeight: Typography.bold,
  },
  patientMeta: { marginTop: 3, fontSize: Typography.xs, color: Colors.gray400 },
  summaryGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginTop: Spacing.xs,
  },
  infoCard: {
    flexGrow: 1,
    flexBasis: Platform.OS === "web" ? "23%" : "47%",
    minWidth: Platform.OS === "web" ? 150 : 136,
    minHeight: 76,
    backgroundColor: Colors.gray50,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    justifyContent: "center",
  },
  infoLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.bold,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  infoValue: {
    fontSize: Typography.md,
    color: Colors.gray800,
    fontWeight: Typography.bold,
    lineHeight: 20,
  },
  planCard: {
    backgroundColor: Colors.gray50,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    marginTop: Spacing.sm,
  },
  planCardHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: Spacing.sm,
  },
  planTitle: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  planEditBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 3,
    backgroundColor: Colors.green50,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 5,
  },
  planEditText: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  planNotes: {
    marginTop: 3,
    fontSize: Typography.xs,
    color: Colors.gray600,
    lineHeight: 17,
  },
  planNutrition: {
    marginTop: 5,
    fontSize: Typography.xs,
    color: Colors.gray800,
    lineHeight: 17,
  },
  planMeta: {
    marginTop: 4,
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.semibold,
  },
  dateRow: { gap: Spacing.xs },
  dateChip: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  dateChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  dateChipText: {
    fontSize: Typography.sm,
    color: Colors.gray400,
    fontWeight: Typography.bold,
  },
  dateChipTextActive: { color: Colors.green600 },
  dateDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: Colors.border,
    alignSelf: "center",
    marginTop: 4,
  },
  dateDotFilled: { backgroundColor: Colors.green400 },
  dateDotActive: { backgroundColor: Colors.green600 },
  weekRegisteredPill: {
    minWidth: 68,
    alignItems: "center",
    borderRadius: Radius.md,
    backgroundColor: Colors.green50,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
  },
  weekRegisteredValue: {
    fontSize: Typography.md,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  weekRegisteredLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    marginTop: -2,
  },
  weekSelector: { gap: Spacing.sm, paddingBottom: Spacing.sm },
  weekChip: {
    minWidth: 132,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  weekChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  weekChipText: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.gray600,
  },
  weekChipTextActive: { color: Colors.green600 },
  weekChipRange: { fontSize: 10, color: Colors.gray400, marginTop: 2 },
  weekChipRangeActive: { color: Colors.green600 },
  weekCompareText: {
    marginTop: Spacing.sm,
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.semibold,
  },
  analysisBlockTitle: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.bold,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginTop: Spacing.md,
    marginBottom: Spacing.sm,
  },
  adherenceGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
  },
  adherenceItem: {
    width: Platform.OS === "web" ? "15.5%" : "31%",
    minHeight: 74,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    backgroundColor: Colors.gray50,
    padding: Spacing.sm,
    justifyContent: "space-between",
  },
  adherenceItemCompact: {
    width: "47.5%",
    flexGrow: 1,
  },
  adherenceTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 6,
  },
  adherenceLabel: {
    flex: 1,
    minWidth: 0,
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.semibold,
  },
  adherenceValue: {
    flexShrink: 0,
    fontSize: Typography.md,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  adherenceWarn: { color: Colors.warning },
  adherenceGood: { color: Colors.green600 },
  adherenceBarBg: {
    height: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.white,
    overflow: "hidden",
    marginTop: Spacing.sm,
  },
  adherenceBarFill: {
    height: 6,
    borderRadius: Radius.full,
    backgroundColor: Colors.green400,
  },
  adherenceBarWarn: { backgroundColor: Colors.warning },
  adherenceBarGood: { backgroundColor: Colors.green600 },
  alertGrid: { flexDirection: "row", flexWrap: "wrap", gap: Spacing.sm },
  alertChip: {
    minWidth: Platform.OS === "web" ? 126 : "47%",
    flex: Platform.OS === "web" ? 1 : undefined,
    borderRadius: Radius.md,
    borderWidth: 1,
    padding: Spacing.sm,
  },
  alertChipGood: {
    backgroundColor: Colors.green50,
    borderColor: Colors.green400,
  },
  alertChipWarn: { backgroundColor: Colors.fatL, borderColor: "#F6C36A" },
  alertValue: { fontSize: Typography.md, fontWeight: Typography.bold },
  alertValueGood: { color: Colors.green600 },
  alertValueWarn: { color: Colors.warning },
  alertLabel: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    marginTop: 2,
    fontWeight: Typography.semibold,
  },
  analysisColumns: {
    flexDirection: Platform.OS === "web" ? "row" : "column",
    gap: Spacing.md,
    marginTop: Spacing.sm,
  },
  analysisColumn: { flex: 1 },
  distributionRow: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingVertical: Spacing.sm,
  },
  distributionTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  distributionName: {
    flex: 1,
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  distributionValue: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  distributionBarBg: {
    height: 6,
    backgroundColor: Colors.gray50,
    borderRadius: Radius.full,
    overflow: "hidden",
    marginTop: 6,
  },
  distributionBarFill: {
    height: 6,
    backgroundColor: Colors.green400,
    borderRadius: Radius.full,
  },
  distributionMeta: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    marginTop: 4,
  },
  topFoodRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingVertical: Spacing.sm,
  },
  topFoodRank: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: Colors.green50,
    color: Colors.green600,
    textAlign: "center",
    lineHeight: 22,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
  },
  topFoodEmoji: { width: 34, alignItems: "center" },
  topFoodInfo: { flex: 1 },
  topFoodName: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  topFoodMeta: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  progressRow: { marginBottom: Spacing.sm },
  progressTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: 5,
  },
  progressLabel: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.semibold,
  },
  progressValue: {
    fontSize: Typography.sm,
    color: Colors.gray600,
    fontWeight: Typography.bold,
  },
  progressOver: { color: Colors.danger },
  progressBg: {
    height: 7,
    borderRadius: Radius.full,
    backgroundColor: Colors.gray50,
    overflow: "hidden",
  },
  progressFill: { height: 7, borderRadius: Radius.full },
  nutritionText: {
    fontSize: Typography.sm,
    color: Colors.gray600,
    lineHeight: 20,
  },
  periodBlock: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    paddingTop: Spacing.sm,
    marginTop: Spacing.sm,
  },
  periodTitle: {
    fontSize: Typography.sm,
    color: Colors.green600,
    fontWeight: Typography.bold,
    marginBottom: Spacing.xs,
  },
  entryRow: {
    flexDirection: "row",
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  entryEmoji: { width: 34, alignItems: "center" },
  entryBody: { flex: 1 },
  entryName: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  entryMeta: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.gray400,
    lineHeight: 16,
  },
  mutedText: { fontSize: Typography.sm, color: Colors.gray400, lineHeight: 18 },
  notificationCard: {
    backgroundColor: Colors.gray50,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  notificationTitle: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.bold,
    marginBottom: 4,
  },
  notificationText: {
    fontSize: Typography.sm,
    color: Colors.gray600,
    lineHeight: 19,
  },
  notificationMeta: {
    marginTop: 4,
    fontSize: Typography.xs,
    color: Colors.gray400,
  },
  emptyState: {
    alignItems: "center",
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.lg,
    padding: Spacing.xl,
  },
  emptyTitle: {
    marginTop: Spacing.sm,
    fontSize: Typography.base,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  emptyText: {
    marginTop: 4,
    fontSize: Typography.sm,
    color: Colors.gray400,
    textAlign: "center",
    lineHeight: 18,
  },
  modalBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  modalTitle: {
    fontSize: Typography.xl,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  modalCloseBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.gray50,
  },
  modalBodyScroll: { flexShrink: 1 },
  modalScroll: { paddingBottom: Spacing.base },
  modalSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  modalHint: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    lineHeight: 17,
    backgroundColor: Colors.gray50,
    borderRadius: Radius.md,
    padding: Spacing.sm,
  },
  fieldGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  fieldWrap: { width: "48%" },
  fieldWrapWide: { width: "100%" },
  lockedPatientField: {
    width: "48%",
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.gray50,
    padding: Spacing.sm,
    minHeight: 66,
    justifyContent: "center",
  },
  lockedPatientFieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.xs,
  },
  lockedPatientValue: {
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
    color: Colors.gray800,
  },
  fieldLabel: {
    fontSize: Typography.xs,
    fontWeight: Typography.semibold,
    color: Colors.gray600,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  fieldBox: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    backgroundColor: Colors.white,
  },
  fieldInput: {
    flex: 1,
    minHeight: 42,
    paddingVertical: Spacing.sm,
    fontSize: Typography.sm,
    color: Colors.gray800,
  },
  fieldSuffix: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    marginLeft: 4,
  },
  timeInputBox: { marginBottom: Spacing.md },
  timePickerButton: {
    minHeight: 44,
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    backgroundColor: Colors.white,
    marginBottom: Spacing.md,
  },
  timePickerText: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.semibold,
  },
  timePickerPlaceholder: { color: Colors.gray400 },
  multilineInput: { minHeight: 96, textAlignVertical: "top" },
  segmentRow: {
    flexDirection: "row",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  segment: {
    flex: 1,
    paddingVertical: Spacing.sm,
    alignItems: "center",
    borderRadius: Radius.md,
    backgroundColor: Colors.gray50,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  segmentActive: {
    backgroundColor: Colors.green50,
    borderColor: Colors.green400,
  },
  segmentText: { color: Colors.gray600, fontWeight: Typography.semibold },
  segmentTextActive: { color: Colors.green600 },
  segmentWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: Spacing.sm,
    marginBottom: Spacing.md,
  },
  pill: {
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.full,
    backgroundColor: Colors.gray50,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  pillActive: { backgroundColor: Colors.green50, borderColor: Colors.green400 },
  pillText: {
    color: Colors.gray600,
    fontWeight: Typography.semibold,
    fontSize: Typography.sm,
  },
  pillTextActive: { color: Colors.green600 },
  recalcBtn: {
    width: 40,
    height: 40,
    borderRadius: Radius.md,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green50,
    borderWidth: 1,
    borderColor: Colors.green400,
  },
  planOptionPanel: {
    marginTop: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  planOptionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: 6,
  },
  planOptionAddBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: Colors.green400,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    backgroundColor: Colors.green50,
  },
  planOptionAddText: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  planOptionTabs: {
    flexDirection: "row",
    gap: 6,
    paddingBottom: 2,
  },
  planOptionTab: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    backgroundColor: Colors.white,
  },
  planOptionTabActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  planOptionTabText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  planOptionTabTextActive: {
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  planSubstitutionNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  planSubstitutionNameInput: {
    flex: 1,
    minHeight: 38,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.white,
    paddingHorizontal: Spacing.sm,
    color: Colors.gray800,
    fontSize: Typography.sm,
  },
  planSubstitutionRemoveBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.proteinL,
    borderWidth: 1,
    borderColor: Colors.protein,
  },
  planFoodSearchPanel: { marginTop: Spacing.sm, marginBottom: Spacing.md },
  planFoodResults: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    overflow: "hidden",
    backgroundColor: Colors.white,
  },
  planFoodOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  planFoodEmoji: { width: 38, alignItems: "center" },
  planFoodInfo: { flex: 1 },
  planFoodName: {
    fontSize: Typography.sm,
    color: Colors.gray800,
    fontWeight: Typography.bold,
  },
  planFoodMeta: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.gray400,
    lineHeight: 16,
  },
  planNutritionChips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
    marginTop: 6,
  },
  planNutritionChip: {
    overflow: "hidden",
    borderRadius: Radius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: 7,
    paddingVertical: 3,
    fontSize: 10,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  planFoodAddBtn: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green400,
  },
  planSelectedBox: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    backgroundColor: Colors.gray50,
    marginTop: Spacing.sm,
    marginBottom: Spacing.sm,
    maxHeight: Platform.OS === "web" ? 280 : 260,
  },
  planSelectedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  planSelectedTotal: {
    fontSize: Typography.sm,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  planSelectedScroll: { flexShrink: 1 },
  planSelectedItem: {
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    marginTop: Spacing.sm,
  },
  planSelectedTop: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.sm,
  },
  planSelectedNameRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.xs,
  },
  planSelectedQtyBadge: {
    maxWidth: "42%",
    overflow: "hidden",
    borderRadius: Radius.full,
    backgroundColor: Colors.green50,
    paddingHorizontal: 8,
    paddingVertical: 3,
    fontSize: 10,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  planSelectedControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  planQtyBox: { width: 72 },
  planQtyInput: {
    minHeight: 34,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    color: Colors.gray800,
    backgroundColor: Colors.white,
  },
  planUnitWrap: { flex: 1, flexDirection: "row", flexWrap: "wrap", gap: 5 },
  planUnitChip: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: Colors.white,
  },
  planUnitChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  planUnitChipText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  planUnitChipTextActive: { color: Colors.green600 },
  patientViewTabs: { paddingBottom: Spacing.sm, gap: 8 },
  patientViewTab: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minHeight: 40,
    paddingHorizontal: Spacing.sm,
    borderRadius: Radius.full,
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  patientViewTabActive: {
    backgroundColor: Colors.green600,
    borderColor: Colors.green600,
  },
  patientViewTabText: {
    color: Colors.green600,
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
  },
  patientViewTabTextActive: { color: Colors.white },
  expandedNutrients: {
    marginTop: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  expandedNutrientsTitle: {
    color: Colors.gray800,
    fontWeight: Typography.bold,
    fontSize: Typography.sm,
    marginBottom: 4,
  },
  expandNutrientsBtn: {
    minHeight: 44,
    marginTop: Spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 4,
    borderRadius: Radius.md,
    backgroundColor: Colors.green50,
  },
  expandNutrientsText: {
    color: Colors.green600,
    fontWeight: Typography.bold,
    fontSize: Typography.sm,
  },
  nutrientLine: {
    height: 3,
    borderRadius: Radius.full,
    backgroundColor: Colors.green50,
    marginTop: 6,
  },
  centerModalBg: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: Spacing.base,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  inviteModalCard: {
    width: "100%",
    maxWidth: 460,
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    padding: Spacing.base,
    ...Shadows.sm,
  },
  inviteModalSubtitle: {
    marginTop: 3,
    maxWidth: 330,
    color: Colors.gray400,
    fontSize: Typography.sm,
    lineHeight: 18,
  },
  inviteModalInputBox: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.sm,
    backgroundColor: Colors.white,
  },
  inviteModalInput: {
    flex: 1,
    minWidth: 0,
    color: Colors.gray800,
    fontSize: Typography.base,
  },
  inviteModalActions: {
    marginTop: Spacing.base,
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: Spacing.sm,
  },
  committedMealsSection: {
    marginTop: Spacing.sm,
    marginBottom: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.green100,
    borderRadius: Radius.md,
    backgroundColor: Colors.green50,
    overflow: "hidden",
  },
  committedMealsSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingTop: Spacing.sm,
    paddingBottom: 4,
  },
  committedMealsSectionLabel: {
    flex: 1,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.green600,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  committedMealRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    borderTopWidth: 1,
    borderTopColor: Colors.green100,
    gap: Spacing.sm,
  },
  committedMealInfo: { flex: 1, minWidth: 0 },
  committedMealTitle: {
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
    color: Colors.gray800,
  },
  committedMealMeta: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.green600,
  },
  committedMealFormLabel: {
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  addMealToPlanBtn: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: Spacing.xs,
    minHeight: 44,
    borderRadius: Radius.md,
    backgroundColor: Colors.green600,
    marginTop: Spacing.sm,
    marginHorizontal: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  addMealToPlanBtnDisabled: { opacity: 0.4 },
  addMealToPlanBtnText: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.white,
  },
});
