import { Platform, StyleSheet } from "react-native";
import { Colors, Radius, Spacing, Typography } from "../../constants/theme";

export const modal = StyleSheet.create({
  bg: { flex: 1, justifyContent: "flex-end" },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0,0,0,0.4)",
  },
  sheet: {
    height: "92%",
    width: "100%",
    maxWidth: Platform.OS === "web" ? 720 : undefined,
    alignSelf: "center",
    backgroundColor: Colors.white,
    borderTopLeftRadius: Radius.xxl,
    borderTopRightRadius: Radius.xxl,
    padding: Spacing.base,
    paddingBottom: Spacing.lg,
  },
  handle: {
    width: 40,
    height: 4,
    backgroundColor: Colors.border,
    borderRadius: 2,
    alignSelf: "center",
    marginBottom: Spacing.base,
    flexShrink: 0,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.base,
    flexShrink: 0,
  },
  body: { flex: 1, minHeight: 0 },
  bodyContent: { paddingBottom: Spacing.lg },
  title: { fontSize: Typography.lg, fontWeight: Typography.bold },
  subtitle: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 3 },
  closePill: {
    backgroundColor: Colors.gray50,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
  },
  closePillText: {
    color: Colors.gray600,
    fontWeight: Typography.semibold,
    fontSize: Typography.sm,
  },
  label: {
    fontSize: Typography.xs,
    fontWeight: Typography.semibold,
    color: Colors.gray400,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  subLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.semibold,
    marginBottom: 6,
  },
  input: {
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    padding: Spacing.md,
    fontSize: Typography.base,
    marginBottom: Spacing.sm,
  },
  searchInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    backgroundColor: Colors.white,
    marginBottom: Spacing.sm,
    paddingLeft: Spacing.md,
    paddingRight: 6,
  },
  searchInputWrapActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  searchInput: {
    flex: 1,
    minHeight: 48,
    paddingVertical: Spacing.sm,
    paddingRight: Spacing.sm,
    fontSize: Typography.base,
    color: Colors.gray800,
  },
  searchMicButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green50,
    borderWidth: 1,
    borderColor: Colors.green100,
  },
  searchMicButtonActive: {
    backgroundColor: Colors.green600,
    borderColor: Colors.green600,
  },
  chipsScroll: { marginBottom: Spacing.sm },
  chips: { flexDirection: "row", gap: 6, paddingRight: Spacing.base },
  chip: {
    backgroundColor: Colors.green50,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  chipContent: { flexDirection: "row", alignItems: "center", gap: 5 },
  chipText: {
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
    color: Colors.green600,
  },
  searchPanel: { flexShrink: 0 },
  suggestionBox: {
    minHeight: 150,
    maxHeight: 280,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    overflow: "hidden",
    marginBottom: Spacing.sm,
    backgroundColor: Colors.white,
  },
  foodOption: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: Spacing.sm,
    padding: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  foodOptionActive: { backgroundColor: Colors.green50 },
  foodEmoji: { width: 38, alignItems: "center", marginTop: 1 },
  foodInfo: { flex: 1 },
  foodActions: {
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    marginLeft: 4,
  },
  foodAddButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green600,
  },
  foodAddButtonDisabled: { opacity: 0.5 },
  foodName: {
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
    color: Colors.gray800,
  },
  foodNameActive: { color: Colors.green600 },
  foodUnit: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  noResults: { padding: Spacing.md, alignItems: "center" },
  noResultsText: { fontSize: Typography.sm, color: Colors.gray400 },
  aiCreateOption: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    padding: Spacing.md,
    backgroundColor: Colors.green50,
  },
  aiIcon: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.green400,
  },
  aiCreateTitle: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  aiCreateText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    marginTop: 2,
    lineHeight: 16,
  },
  bottomPanel: {
    flexShrink: 0,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.white,
  },
  emptySelection: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    backgroundColor: Colors.green50,
  },
  emptySelectionText: {
    flex: 1,
    fontSize: Typography.sm,
    color: Colors.gray600,
    lineHeight: 18,
    fontWeight: Typography.semibold,
  },
  unitChip: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  unitChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  unitChipText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  unitChipTextActive: { color: Colors.green600 },
  selectedBox: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    marginBottom: Spacing.sm,
    overflow: "hidden",
  },
  selectedHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: Spacing.sm,
    paddingVertical: 8,
    backgroundColor: Colors.gray50,
  },
  selectedTitle: {
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.gray600,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  selectedTotal: {
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  selectedItem: {
    padding: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.white,
  },
  selectedTopRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  selectedEmoji: { width: 34, alignItems: "center" },
  selectedInfo: { flex: 1 },
  selectedName: {
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
    color: Colors.gray800,
  },
  selectedMeta: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.gray400,
  },
  selectedRemove: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.gray50,
  },
  selectedControls: {
    flexDirection: "row",
    gap: Spacing.sm,
    alignItems: "flex-start",
    marginTop: Spacing.sm,
  },
  selectedQtyField: { width: 82 },
  inlineLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.bold,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  selectedQtyInput: {
    height: 38,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    fontSize: Typography.sm,
    color: Colors.gray800,
    backgroundColor: Colors.white,
  },
  selectedUnits: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    paddingTop: 18,
  },
  periodBox: { marginBottom: Spacing.sm },
  periodRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  periodChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 8,
    backgroundColor: Colors.white,
  },
  periodChipActive: {
    backgroundColor: Colors.green400,
    borderColor: Colors.green400,
  },
  periodText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  periodTextActive: { color: Colors.white },

  qtyPickerPanel: {
    borderTopWidth: 2,
    borderTopColor: Colors.green400,
    backgroundColor: Colors.green50,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.sm,
    flexShrink: 0,
  },
  qtyPickerHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.xs,
  },
  qtyPickerName: {
    flex: 1,
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  qtyPickerNutritionText: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.semibold,
    marginBottom: Spacing.sm,
  },
  qtyPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  qtyPickerInputWrap: {
    width: 78,
    height: 42,
    borderWidth: 1.5,
    borderColor: Colors.green400,
    borderRadius: Radius.sm,
    backgroundColor: Colors.white,
    justifyContent: 'center',
    paddingHorizontal: Spacing.sm,
  },
  qtyPickerInput: {
    fontSize: Typography.base,
    color: Colors.gray800,
    paddingVertical: 0,
  },
  qtyPickerUnitsScroll: { flex: 1 },
  qtyPickerUnits: { flexDirection: 'row', gap: 6, paddingRight: Spacing.sm },
  qtyPickerActions: {
    flexDirection: 'row',
    gap: Spacing.sm,
    marginTop: 2,
  },
  qtyPickerAddBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
    borderWidth: 1.5,
    borderColor: Colors.green400,
    borderRadius: Radius.md,
    paddingVertical: 10,
    backgroundColor: Colors.white,
  },
  qtyPickerAddBtnText: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  qtyPickerFinishBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    paddingVertical: 10,
    backgroundColor: Colors.green600,
  },
  qtyPickerFinishBtnDisabled: { opacity: 0.5 },
  qtyPickerFinishBtnText: {
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.white,
  },

  nutritionSummary: {
    marginTop: 4,
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  nutritionMicroSummary: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.gray400,
  },

  actions: {
    flexDirection: "row",
    gap: Spacing.sm,
    paddingTop: Spacing.sm,
    borderTopWidth: 1,
    borderTopColor: Colors.border,
    backgroundColor: Colors.white,
    flexShrink: 0,
  },
  btnCancel: {
    flex: 1,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    paddingVertical: 13,
    alignItems: "center",
  },
  btnCancelText: { fontSize: Typography.base, color: Colors.gray600 },
  btnAdd: {
    flex: 2,
    backgroundColor: Colors.green400,
    borderRadius: Radius.md,
    paddingVertical: 13,
    alignItems: "center",
  },
  btnDisabled: { opacity: 0.4 },
  btnAddText: {
    color: Colors.white,
    fontSize: Typography.base,
    fontWeight: Typography.bold,
  },
});

export const voiceModal = StyleSheet.create({
  circle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: Colors.purpleL,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    borderWidth: 3,
    borderColor: Colors.purple,
    marginVertical: Spacing.md,
  },
  circleActive: { backgroundColor: Colors.purple },
  tip: {
    textAlign: "center",
    fontSize: Typography.sm,
    color: Colors.gray400,
    marginBottom: Spacing.sm,
  },
  transcript: {
    backgroundColor: Colors.gray50,
    borderRadius: Radius.sm,
    padding: Spacing.md,
    minHeight: 60,
    marginBottom: Spacing.md,
  },
  transcriptText: { fontSize: Typography.md, color: Colors.gray800 },
  exTitle: {
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 6,
  },
  example: {
    fontSize: Typography.sm,
    color: Colors.gray600,
    fontStyle: "italic",
    marginBottom: 4,
    backgroundColor: Colors.gray50,
    borderRadius: 6,
    padding: 6,
  },
  previewBox: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    marginBottom: Spacing.md,
  },
  previewEmpty: {
    fontSize: Typography.sm,
    color: Colors.gray400,
    lineHeight: 18,
  },
  previewRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
  },
  previewEmoji: { width: 40, alignItems: "center" },
  previewInfo: { flex: 1 },
  previewName: {
    fontSize: Typography.md,
    fontWeight: Typography.bold,
    color: Colors.gray800,
  },
  previewMeta: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  editCard: {
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingVertical: Spacing.sm,
  },
  editHeader: { flexDirection: "row", alignItems: "center", gap: Spacing.sm },
  foodInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    fontSize: Typography.sm,
    color: Colors.gray800,
    backgroundColor: Colors.white,
  },
  inputError: { borderColor: Colors.danger, backgroundColor: Colors.proteinL },
  errorText: { fontSize: Typography.xs, color: Colors.danger, marginTop: 3 },
  aiCreateBtn: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    gap: 5,
    marginTop: 6,
    borderWidth: 1,
    borderColor: Colors.green400,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
    backgroundColor: Colors.green50,
  },
  aiCreateText: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.bold,
  },
  removeBtn: {
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.gray50,
  },
  editRow: { flexDirection: "row", gap: Spacing.sm, marginTop: Spacing.sm },
  quantityEdit: { width: 86 },
  unitEdit: { flex: 1 },
  smallLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    fontWeight: Typography.semibold,
    marginBottom: 4,
  },
  quantityInput: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    fontSize: Typography.sm,
    color: Colors.gray800,
  },
  unitRow: { flexDirection: "row", gap: 6, paddingRight: Spacing.sm },
  unitMiniChip: {
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
    backgroundColor: Colors.white,
  },
  unitMiniChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  unitMiniText: {
    fontSize: Typography.xs,
    color: Colors.gray600,
    fontWeight: Typography.semibold,
  },
  unitMiniTextActive: { color: Colors.green600 },
  spokenText: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    marginTop: 3,
    fontStyle: "italic",
  },
});
