import { Platform, StyleSheet } from "react-native";
import { Colors, Radius, Spacing, Typography } from "../../constants/theme";
import { VIEWPORT_POSITION } from "./types";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    position: "relative",
    backgroundColor: Colors.bg,
  },
  pageScroll: { flex: 1 },
  headerBar: {
    width: "100%",
    maxWidth: Platform.OS === "web" ? 760 : undefined,
    alignSelf: "center",
    backgroundColor: Colors.white,
    padding: Spacing.base,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: Spacing.sm,
    zIndex: 20,
  },
  headerTitle: { fontSize: Typography.lg, fontWeight: Typography.bold },
  headerSubtitle: {
    marginTop: 2,
    fontSize: Typography.xs,
    color: Colors.warning,
    fontWeight: Typography.semibold,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
  },
  pendingPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: Colors.fatL,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 6,
  },
  pendingPillText: {
    color: Colors.warning,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
  },
  syncedPill: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green50,
  },
  fabBackdrop: {
    position: VIEWPORT_POSITION,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 40,
  },
  fabLayer: {
    position: VIEWPORT_POSITION,
    left: 0,
    right: 0,
    zIndex: 50,
    elevation: 20,
  },
  fabInner: {
    width: "100%",
    maxWidth: Platform.OS === "web" ? 760 : undefined,
    alignSelf: "center",
    alignItems: "flex-end",
    paddingHorizontal: Spacing.base,
  },
  fabActions: {
    alignItems: "flex-end",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  fabActionItem: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: Spacing.sm,
  },
  fabActionDisabled: { opacity: 0.45 },
  fabActionLabel: {
    backgroundColor: Colors.white,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.border,
    paddingHorizontal: Spacing.md,
    paddingVertical: 9,
    elevation: 4,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
  },
  fabActionText: {
    color: Colors.gray800,
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
  },
  fabActionButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.white,
    borderWidth: 1,
    borderColor: Colors.green400,
    elevation: 5,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
  },
  fabButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.green400,
    borderWidth: 1,
    borderColor: Colors.green400,
    elevation: 10,
    shadowColor: "#000",
    shadowOpacity: 0.22,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
  },
  fabButtonOpen: {
    backgroundColor: Colors.green600,
    borderColor: Colors.green600,
  },
  scroll: {
    width: "100%",
    maxWidth: Platform.OS === "web" ? 760 : undefined,
    alignSelf: "center",
    padding: Spacing.base,
    paddingBottom: Spacing.xl,
  },

  sectionLabel: {
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.gray400,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: Spacing.sm,
  },

  datePanel: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  datePanelHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  datePanelTitle: {
    fontSize: Typography.base,
    fontWeight: Typography.bold,
    color: Colors.gray800,
    textTransform: "capitalize",
  },
  dateTotalPill: {
    minWidth: 68,
    alignItems: "center",
    borderRadius: Radius.md,
    backgroundColor: Colors.green50,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 7,
  },
  dateTotalKcal: {
    fontSize: Typography.md,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  dateTotalLabel: {
    fontSize: Typography.xs,
    color: Colors.gray400,
    marginTop: -2,
  },
  dateChips: {
    flexDirection: "row",
    gap: Spacing.sm,
    paddingRight: Spacing.sm,
  },
  dateChip: {
    width: 56,
    minHeight: 72,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.white,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
  },
  dateChipActive: {
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
  },
  dateChipWeekday: {
    fontSize: 10,
    color: Colors.gray400,
    textTransform: "uppercase",
    fontWeight: Typography.semibold,
  },
  dateChipDay: {
    fontSize: Typography.lg,
    color: Colors.gray800,
    fontWeight: Typography.bold,
    marginTop: 2,
  },
  dateChipTextActive: { color: Colors.green600 },
  dateChipDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: Colors.border,
    marginTop: 5,
  },
  dateChipDotFilled: { backgroundColor: Colors.green400 },
  dateChipDotActive: { backgroundColor: Colors.green600 },

  savedCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  savedLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    flex: 1,
  },
  savedEmoji: { width: 38, alignItems: "center" },
  savedName: { fontSize: Typography.md, fontWeight: Typography.semibold },
  savedInfo: { fontSize: Typography.xs, color: Colors.gray400 },
  quickAddBtn: {
    backgroundColor: Colors.green50,
    borderRadius: Radius.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderWidth: 1,
    borderColor: Colors.green400,
  },
  quickAddTxt: {
    color: Colors.green600,
    fontSize: Typography.sm,
    fontWeight: Typography.semibold,
  },

  emptyLog: { alignItems: "center", padding: Spacing.xl },
  emptyLogText: { color: Colors.gray400, fontSize: Typography.md },

  logList: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: "hidden",
  },
});

export const logStyle = StyleSheet.create({
  group: { borderBottomWidth: 1, borderBottomColor: Colors.border },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.xs,
    backgroundColor: Colors.green50,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  groupTitle: {
    flex: 1,
    fontSize: Typography.sm,
    fontWeight: Typography.bold,
    color: Colors.green600,
  },
  groupCount: {
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.green600,
    backgroundColor: Colors.white,
    borderRadius: Radius.full,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    padding: Spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    gap: Spacing.sm,
  },
  emoji: { width: 40, alignItems: "center" },
  info: { flex: 1 },
  infoTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: Spacing.sm,
    marginBottom: 2,
  },
  periodBadge: {
    backgroundColor: Colors.green50,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  periodTxt: {
    fontSize: Typography.xs,
    color: Colors.green600,
    fontWeight: Typography.semibold,
  },
  timeBadge: {
    backgroundColor: Colors.gray50,
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  timeTxt: { fontSize: Typography.xs, color: Colors.gray400 },
  name: { fontSize: Typography.md, fontWeight: Typography.semibold },
  macros: { fontSize: Typography.xs, color: Colors.gray400 },
  right: { alignItems: "flex-end", gap: 2 },
  kcal: { fontSize: Typography.md, fontWeight: Typography.bold },
  kcalLabel: { fontSize: Typography.xs, color: Colors.gray400 },
  editBtn: {
    marginTop: 4,
    padding: 4,
    borderRadius: Radius.full,
    backgroundColor: Colors.green50,
  },
  delBtn: { marginTop: 4, padding: 4 },
  delTxt: { color: Colors.gray400, fontSize: Typography.sm },
});
