import { Platform, StyleSheet } from 'react-native';
import { Colors, Radius, Shadows, Spacing, Typography } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  headerBar: { width: '100%', maxWidth: Platform.OS === 'web' ? 900 : undefined, alignSelf: 'center', backgroundColor: Colors.white, padding: Spacing.base, borderBottomWidth: 1, borderBottomColor: Colors.border },
  headerTitle: { fontSize: Typography.lg, fontWeight: Typography.bold },
  headerSub: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  scroll: { width: '100%', maxWidth: Platform.OS === 'web' ? 900 : undefined, alignSelf: 'center', padding: Spacing.base, paddingBottom: 110 },
  loadingBox: { alignItems: 'center', padding: Spacing.xl, gap: Spacing.sm },
  emptyBox: { backgroundColor: Colors.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.lg },
  emptyTitle: { fontSize: Typography.md, fontWeight: Typography.bold, marginBottom: Spacing.xs },
  emptyText: { fontSize: Typography.sm, color: Colors.gray400, lineHeight: 20 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.sm },
  statCard: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    padding: Spacing.md,
    ...Shadows.sm,
  },
  statLabel: { fontSize: Typography.xs, color: Colors.gray400, fontWeight: Typography.semibold },
  statValue: { fontSize: Typography.lg, fontWeight: Typography.bold, marginTop: 4 },
  statHint: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 3 },
  section: { backgroundColor: Colors.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.md, marginBottom: Spacing.sm },
  sectionCompact: { padding: Spacing.sm },
  sectionTitle: { fontSize: Typography.base, fontWeight: Typography.bold, marginBottom: 4 },
  weekAnalysisHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: Spacing.sm, marginBottom: Spacing.sm },
  weekAnalysisHeaderCompact: { flexDirection: 'column' },
  weekAnalysisSub: { fontSize: Typography.xs, color: Colors.gray400 },
  weekRegisteredPill: { minWidth: 68, alignItems: 'center', borderRadius: Radius.md, backgroundColor: Colors.green50, paddingHorizontal: Spacing.sm, paddingVertical: 7 },
  weekRegisteredValue: { fontSize: Typography.md, fontWeight: Typography.bold, color: Colors.green600 },
  weekRegisteredLabel: { fontSize: Typography.xs, color: Colors.gray400, marginTop: -2 },
  weekSelectorScroll: { marginBottom: Spacing.sm },
  weekSelector: { flexDirection: 'row', gap: Spacing.sm, paddingRight: Spacing.sm },
  weekChip: { minWidth: 132, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, paddingHorizontal: Spacing.sm, paddingVertical: 8, backgroundColor: Colors.white },
  weekChipCompact: { minWidth: 118, paddingHorizontal: 10 },
  weekChipActive: { borderColor: Colors.green400, backgroundColor: Colors.green50 },
  weekChipText: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray600 },
  weekChipTextActive: { color: Colors.green600 },
  weekChipRange: { fontSize: 10, color: Colors.gray400, marginTop: 2 },
  weekChipRangeActive: { color: Colors.green600 },
  weekSummaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginBottom: Spacing.sm },
  weekBlockTitle: { fontSize: Typography.xs, color: Colors.gray600, fontWeight: Typography.bold, textTransform: 'uppercase', letterSpacing: 0.5, marginTop: Spacing.sm, marginBottom: Spacing.sm },
  adherenceGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  adherenceItem: { minHeight: 68, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, backgroundColor: Colors.gray50, padding: Spacing.sm, justifyContent: 'center' },
  adherenceLabel: { fontSize: Typography.xs, color: Colors.gray400, fontWeight: Typography.semibold },
  adherenceValue: { fontSize: Typography.lg, color: Colors.gray800, fontWeight: Typography.bold, marginTop: 4 },
  adherenceWarn: { color: Colors.warning },
  adherenceGood: { color: Colors.green600 },
  alertGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  alertChip: { minWidth: 0, borderRadius: Radius.md, borderWidth: 1, padding: Spacing.sm },
  alertChipGood: { backgroundColor: Colors.green50, borderColor: Colors.green400 },
  alertChipWarn: { backgroundColor: Colors.fatL, borderColor: '#F6C36A' },
  alertValue: { fontSize: Typography.md, fontWeight: Typography.bold },
  alertValueGood: { color: Colors.green600 },
  alertValueWarn: { color: Colors.warning },
  alertLabel: { fontSize: Typography.xs, color: Colors.gray600, marginTop: 2, fontWeight: Typography.semibold },
  weekColumns: { flexDirection: Platform.OS === 'web' ? 'row' : 'column', gap: Spacing.md, marginTop: Spacing.sm },
  weekColumnsCompact: { flexDirection: 'column', gap: Spacing.sm },
  weekColumn: { flex: 1 },
  distributionRow: { borderTopWidth: 1, borderTopColor: Colors.border, paddingVertical: Spacing.sm },
  distributionTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  distributionName: { flex: 1, fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray800 },
  distributionValue: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.green600 },
  distributionBarBg: { height: 6, backgroundColor: Colors.gray50, borderRadius: Radius.full, overflow: 'hidden', marginTop: 6 },
  distributionBarFill: { height: 6, backgroundColor: Colors.green400, borderRadius: Radius.full },
  distributionMeta: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 4 },
  topFoodRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, borderTopWidth: 1, borderTopColor: Colors.border, paddingVertical: Spacing.sm },
  topFoodRank: { width: 22, height: 22, borderRadius: 11, backgroundColor: Colors.green50, color: Colors.green600, textAlign: 'center', lineHeight: 22, fontSize: Typography.xs, fontWeight: Typography.bold },
  topFoodEmoji: { width: 34, alignItems: 'center' },
  topFoodInfo: { flex: 1 },
  topFoodName: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray800 },
  topFoodMeta: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  nutritionPanel: {
    backgroundColor: Colors.white,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Colors.border,
    overflow: 'hidden',
    marginBottom: Spacing.sm,
    ...Shadows.sm,
  },
  nutritionHeader: { padding: Spacing.md, borderBottomWidth: 1, borderBottomColor: Colors.border },
  nutritionTitle: { fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.gray800 },
  nutritionSubtitle: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  nutritionSection: { borderBottomWidth: 1, borderBottomColor: Colors.border },
  nutritionSectionTitle: {
    paddingHorizontal: Spacing.md,
    paddingTop: Spacing.sm,
    paddingBottom: 6,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    color: Colors.green600,
    textTransform: 'uppercase',
    letterSpacing: 0.4,
    backgroundColor: Colors.green50,
  },
  nutritionRow: { paddingHorizontal: Spacing.md, paddingVertical: Spacing.sm, borderTopWidth: 1, borderTopColor: Colors.border },
  nutritionRowTop: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm },
  nutritionName: { flex: 1, fontSize: Typography.sm, fontWeight: Typography.semibold, color: Colors.gray800 },
  nutritionValues: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray800 },
  nutritionGoalText: { fontSize: Typography.xs, fontWeight: Typography.regular, color: Colors.gray400 },
  nutritionMetaRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginTop: 6 },
  nutritionBarBg: { flex: 1, height: 6, backgroundColor: Colors.gray50, borderRadius: Radius.full, overflow: 'hidden' },
  nutritionBarFill: { height: 6, borderRadius: Radius.full },
  nutritionStatus: {
    minWidth: 78,
    overflow: 'hidden',
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    paddingVertical: 3,
    fontSize: Typography.xs,
    fontWeight: Typography.bold,
    textAlign: 'center',
  },
});
