import { Platform, StyleSheet } from 'react-native';
import { Colors, Radius, Shadows, Spacing, Typography } from '../../constants/theme';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: Colors.bg },
  header: {
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 760 : undefined,
    alignSelf: 'center',
    backgroundColor: Colors.white,
    borderBottomWidth: 1,
    borderBottomColor: Colors.border,
    paddingHorizontal: Spacing.base,
    paddingVertical: Spacing.md,
  },
  headerTop: { flexDirection: 'row', alignItems: 'flex-start', gap: Spacing.sm },
  headerTitleWrap: { flex: 1, minWidth: 0 },
  headerFriendsButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.green50,
    borderWidth: 1,
    borderColor: Colors.green100,
    position: 'relative',
  },
  headerFriendsBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 19,
    height: 19,
    overflow: 'hidden',
    borderRadius: 10,
    backgroundColor: Colors.green600,
    color: Colors.white,
    textAlign: 'center',
    paddingHorizontal: 5,
    fontSize: 10,
    fontWeight: Typography.bold,
    lineHeight: 19,
  },
  eyebrow: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold, textTransform: 'uppercase', letterSpacing: 0.5 },
  title: { fontSize: Typography.xl, fontWeight: Typography.bold, color: Colors.gray800 },
  subtitle: { marginTop: 2, fontSize: Typography.sm, color: Colors.gray400, lineHeight: 18 },
  scroll: { width: '100%', maxWidth: Platform.OS === 'web' ? 760 : undefined, alignSelf: 'center', padding: Spacing.base, paddingBottom: 110 },
  filterBar: { flexDirection: 'row', gap: Spacing.sm, marginBottom: Spacing.sm },
  filterBtn: {
    flex: 1,
    minHeight: 46,
    borderRadius: Radius.full,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.xs,
  },
  filterBtnActive: { backgroundColor: Colors.green50, borderColor: Colors.green100 },
  filterText: { fontSize: Typography.sm, fontWeight: Typography.bold, color: Colors.gray400 },
  filterTextActive: { color: Colors.green600 },
  friendsModalOverlay: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(8, 80, 65, 0.22)' },
  friendsModalBackdrop: { ...StyleSheet.absoluteFillObject },
  friendsModalSheet: {
    width: '100%',
    maxWidth: 620,
    maxHeight: '82%',
    alignSelf: 'center',
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    backgroundColor: Colors.white,
    paddingTop: Spacing.sm,
  },
  friendsModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, paddingHorizontal: Spacing.md, paddingBottom: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border },
  friendsModalTitle: { fontSize: Typography.lg, color: Colors.gray800, fontWeight: Typography.bold },
  friendsModalSubtitle: { marginTop: 2, fontSize: Typography.xs, color: Colors.gray400 },
  friendsModalClose: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray50 },
  friendsModalContent: { padding: Spacing.md, paddingBottom: Spacing.xl },
  friendsModalListHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: Spacing.sm, marginTop: Spacing.sm, marginBottom: Spacing.xs },
  friendsTitle: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  friendsCount: { minWidth: 26, overflow: 'hidden', borderRadius: Radius.full, backgroundColor: Colors.green50, color: Colors.green600, textAlign: 'center', paddingHorizontal: 7, paddingVertical: 2, fontSize: Typography.xs, fontWeight: Typography.bold },
  friendSearchRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, marginBottom: Spacing.xs },
  friendSearchInputWrap: { flex: 1, minHeight: 42, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.gray50, flexDirection: 'row', alignItems: 'center', paddingHorizontal: Spacing.sm },
  friendSearchPrefix: { fontSize: Typography.md, color: Colors.green600, fontWeight: Typography.bold, marginRight: 2 },
  friendSearchInput: { flex: 1, minHeight: 40, paddingVertical: 0, fontSize: Typography.sm, color: Colors.gray800 },
  friendSearchButton: { width: 42, height: 42, borderRadius: Radius.md, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green600 },
  friendSearchFeedback: { fontSize: Typography.xs, color: Colors.danger, marginBottom: Spacing.xs },
  friendResult: { minHeight: 54, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.green100, backgroundColor: Colors.green50, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, padding: Spacing.xs, marginBottom: Spacing.xs },
  friendResultInfo: { flex: 1, minWidth: 0 },
  friendResultName: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  friendResultNickname: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.semibold },
  friendResultButton: { minHeight: 34, borderRadius: Radius.full, backgroundColor: Colors.green600, alignItems: 'center', justifyContent: 'center', paddingHorizontal: Spacing.sm },
  friendResultButtonActive: { backgroundColor: Colors.white, borderWidth: 1, borderColor: Colors.green100 },
  friendResultButtonText: { fontSize: Typography.xs, color: Colors.white, fontWeight: Typography.bold },
  friendResultButtonTextActive: { color: Colors.green600 },
  friendsEmpty: { fontSize: Typography.sm, color: Colors.gray400, lineHeight: 18 },
  friendsModalList: { gap: Spacing.xs },
  friendListItem: { minHeight: 58, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white, padding: Spacing.sm },
  friendAvatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  friendAvatarText: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold },
  postCard: { backgroundColor: Colors.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, overflow: 'visible', marginBottom: Spacing.sm, zIndex: 1, ...Shadows.sm },
  postHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, padding: Spacing.md, zIndex: 30 },
  avatar: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50 },
  avatarText: { color: Colors.green600, fontWeight: Typography.bold },
  postAuthorWrap: { flex: 1 },
  postAuthor: { fontSize: Typography.md, fontWeight: Typography.bold, color: Colors.gray800 },
  postNickname: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.semibold, marginTop: 1 },
  postMeta: { fontSize: Typography.xs, color: Colors.gray400, marginTop: 2 },
  postMenuWrap: { position: 'relative', zIndex: 40 },
  postMenuButton: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.gray50 },
  postMenu: {
    position: 'absolute',
    top: 38,
    right: 0,
    width: 164,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Colors.border,
    backgroundColor: Colors.white,
    paddingVertical: 4,
    zIndex: 100,
    ...Shadows.md,
  },
  postMenuItem: { minHeight: 40, flexDirection: 'row', alignItems: 'center', gap: Spacing.xs, paddingHorizontal: Spacing.sm },
  postMenuText: { flex: 1, fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.semibold },
  postMenuTextDanger: { color: Colors.danger },
  followBtn: {
    minHeight: 34,
    borderRadius: Radius.full,
    paddingHorizontal: Spacing.sm,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: Colors.green400,
    borderWidth: 1,
    borderColor: Colors.green400,
  },
  followBtnActive: { backgroundColor: Colors.green50, borderColor: Colors.green100 },
  followText: { fontSize: Typography.xs, fontWeight: Typography.bold, color: Colors.white },
  followTextActive: { color: Colors.green600 },
  postImageFrame: { width: '100%', aspectRatio: 1, maxHeight: 520, overflow: 'hidden', backgroundColor: Colors.gray50 },
  postImage: { width: '100%', height: '100%' },
  postBody: { padding: Spacing.md, borderBottomWidth: 1, borderBottomColor: Colors.border },
  caption: { fontSize: Typography.sm, color: Colors.gray800, lineHeight: 19, marginTop: 4 },
  taggedText: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold, marginBottom: 6 },
  foodNames: { fontSize: Typography.md, fontWeight: Typography.bold, color: Colors.gray800, marginBottom: 4 },
  nutritionText: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 20 },
  commentBlock: { padding: Spacing.md },
  commentItem: { marginBottom: Spacing.xs },
  commentAuthor: { fontSize: Typography.xs, fontWeight: Typography.bold, color: Colors.green600 },
  commentMessage: { fontSize: Typography.sm, color: Colors.gray600, lineHeight: 18 },
  noComments: { fontSize: Typography.sm, color: Colors.gray400, marginBottom: Spacing.sm },
  commentInputRow: { flexDirection: 'row', gap: Spacing.sm, alignItems: 'center', marginTop: Spacing.xs },
  commentInput: { flex: 1, borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.full, paddingHorizontal: Spacing.md, paddingVertical: Platform.OS === 'web' ? Spacing.sm : 8, fontSize: Typography.sm, color: Colors.gray800 },
  commentSend: { width: 36, height: 36, borderRadius: 18, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green400 },
  communityFab: {
    position: 'absolute',
    right: Spacing.base,
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.green400,
    backgroundColor: Colors.green50,
    ...Shadows.md,
  },
  emptyState: { alignItems: 'center', backgroundColor: Colors.white, borderRadius: Radius.lg, borderWidth: 1, borderColor: Colors.border, padding: Spacing.xl },
  emptyTitle: { marginTop: Spacing.sm, fontSize: Typography.base, fontWeight: Typography.bold, color: Colors.gray800 },
  emptyText: { marginTop: 4, fontSize: Typography.sm, color: Colors.gray400, lineHeight: 20, textAlign: 'center' },
});

export const modalStyles = StyleSheet.create({
  content: { paddingHorizontal: Spacing.md, paddingBottom: Spacing.md },
  label: { fontSize: Typography.xs, color: Colors.gray400, fontWeight: Typography.bold, textTransform: 'uppercase', letterSpacing: 0.4, marginTop: Spacing.sm, marginBottom: 6 },
  captionInput: {
    minHeight: 86,
    borderWidth: 1,
    borderColor: Colors.border,
    borderRadius: Radius.md,
    padding: Spacing.sm,
    fontSize: Typography.sm,
    color: Colors.gray800,
    textAlignVertical: 'top',
    backgroundColor: Colors.white,
  },
  postPreviewFrame: { width: '100%', aspectRatio: 1, borderRadius: Radius.md, overflow: 'hidden', backgroundColor: Colors.gray50 },
  postPreview: { width: '100%', height: '100%' },
  emptyPhoto: { width: '100%', aspectRatio: 1, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.gray50, alignItems: 'center', justifyContent: 'center', padding: Spacing.md },
  emptyPhotoText: { marginTop: Spacing.xs, fontSize: Typography.sm, color: Colors.gray400, textAlign: 'center' },
  photoButtons: { flexDirection: 'row', gap: Spacing.sm, marginTop: Spacing.sm },
  photoButton: { flex: 1, minHeight: 42, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.green100, backgroundColor: Colors.green50, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs },
  photoButtonText: { fontSize: Typography.sm, color: Colors.green600, fontWeight: Typography.bold },
  aiButton: { minHeight: 44, borderRadius: Radius.md, backgroundColor: Colors.green400, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: Spacing.xs, marginTop: Spacing.sm },
  aiButtonDisabled: { opacity: 0.65 },
  aiButtonText: { color: Colors.white, fontSize: Typography.sm, fontWeight: Typography.bold },
  detectedBox: { borderWidth: 1, borderColor: Colors.border, borderRadius: Radius.md, padding: Spacing.sm, marginTop: Spacing.sm, backgroundColor: Colors.gray50 },
  detectedTitle: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold, marginBottom: 4 },
  detectedRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingVertical: 6, borderTopWidth: 1, borderTopColor: Colors.border },
  detectedInfo: { flex: 1 },
  detectedName: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  detectedMeta: { marginTop: 2, fontSize: Typography.xs, color: Colors.gray600 },
  detectedConfidence: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold },
  detectedTotal: { marginTop: Spacing.xs, fontSize: Typography.xs, color: Colors.gray600, fontWeight: Typography.semibold },
  visibilityRow: { flexDirection: 'row', gap: Spacing.xs },
  visibilityChip: { flex: 1, minHeight: 40, borderRadius: Radius.full, borderWidth: 1, borderColor: Colors.border, backgroundColor: Colors.white, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 },
  visibilityChipActive: { borderColor: Colors.green100, backgroundColor: Colors.green50 },
  visibilityText: { fontSize: Typography.xs, color: Colors.gray400, fontWeight: Typography.bold },
  visibilityTextActive: { color: Colors.green600 },
  emptyFriendsText: { fontSize: Typography.sm, color: Colors.gray400, lineHeight: 18 },
  tagResults: { marginTop: Spacing.xs, borderRadius: Radius.md, borderWidth: 1, borderColor: Colors.border, overflow: 'hidden' },
  tagResultRow: { minHeight: 52, flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, paddingHorizontal: Spacing.sm, backgroundColor: Colors.white, borderBottomWidth: 1, borderBottomColor: Colors.border },
  tagAvatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  tagAvatarText: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.bold },
  tagResultInfo: { flex: 1, minWidth: 0 },
  tagResultName: { fontSize: Typography.sm, color: Colors.gray800, fontWeight: Typography.bold },
  tagResultNickname: { fontSize: Typography.xs, color: Colors.green600, fontWeight: Typography.semibold },
  taggedAvatars: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm, marginTop: Spacing.sm },
  taggedAvatarWrap: { width: 44, height: 44, position: 'relative' },
  taggedAvatar: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.green50, borderWidth: 1, borderColor: Colors.green100 },
  taggedRemoveBadge: { position: 'absolute', top: -3, right: -3, width: 18, height: 18, borderRadius: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: Colors.danger, borderWidth: 2, borderColor: Colors.white },
});
